twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        delete_trick_by_owner_only: '%trick.delete.by_owner_only%'
        update_trick_by_owner_only: '%trick.update.by_owner_only%'

when@test:
    twig:
        strict_variables: true
