controllers:
    resource: ../src/Controller/
    type: attribute

api:
    resource: ../src/Controller/Api
    type: attribute
    prefix: /api
    name_prefix: api_

index:
    path: /
    controller: App\Controller\TrickController::list
