parameters:
  mailer.sender: 'noreply@snowtricks.com'
  trick.delete.by_owner_only: true

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      bool $deleteTrickByOwnerOnly: '%trick.delete.by_owner_only%'

  _instanceof:
    App\Mailer\EmailInterface:
      tags: [ 'app.mailer.email' ]

    App\Doctrine\Type\AbstractEnumType:
      tags: [ 'app.doctrine.enum_type' ]

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Mailer\EmailSender:
    arguments:
      $sender: '%mailer.sender%'
      $container: !tagged_locator app.mailer.email
