parameters:
  mailer.sender: 'noreply@snowtricks.com'
  trick.delete.by_owner_only: true
  trick.update.by_owner_only: false
  uploads_dir: '%kernel.project_dir%/public/uploads'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      bool $deleteTrickByOwnerOnly: '%trick.delete.by_owner_only%'
      bool $updateTrickByOwnerOnly: '%trick.update.by_owner_only%'
      string $uploadsDir: '%uploads_dir%'

  _instanceof:
    App\Mailer\Email\EmailInterface:
      tags: [ 'app.mailer.email' ]

    App\Doctrine\Type\AbstractEnumType:
      tags: [ 'app.doctrine.enum_type' ]

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Doctrine/Entity/'
      - '../src/Kernel.php'

  App\Mailer\EmailSender:
    arguments:
      $sender: '%mailer.sender%'
      $container: !tagged_locator app.mailer.email
